default-target = "wasm32-unknown-emscripten"

[target.emscripten]
link-args = ["-s", "USE_SDL=2", 
             "-s", "USE_SDL_MIXER=2",
             "-s", "USE_SDL_IMAGE=2",
             "-s", "SDL2_IMAGE_FORMATS='[\"png\"]'",
             "-s", "USE_WEBGL2=1"]
